---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      name: metrics-server
      labels:
        k8s-app: metrics-server
    spec:
      hostNetwork: true
      imagePullSecrets:
      - name: myregistrykey
      serviceAccountName: metrics-server
      volumes:
      - name: tmp-dir
        emptyDir: {}
      - name: kubelet-certs
        secret:
          secretName: kubelet-secret
      containers:
      - name: metrics-server
        image: registry-qcc.quantil.com/qcc/metrics-server-amd64:v0.3.6-ecp
        imagePullPolicy: Always
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: qcc-api-la2-mgt.quantil.com
        args:
        - --kubelet-preferred-address-types=InternalIP,InternalDNS,Hostname,ExternalIP,ExternalDNS
        - --kubelet-cert-file=/etc/kubelet/kube-client.pem
        - --kubelet-key-file=/etc/kubelet/kube-client-key.pem
        - --kubelet-insecure-tls=true
        - --secure-port=18443
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
        - name: kubelet-certs
          mountPath: /etc/kubelet
---
apiVersion: v1
data:
  kube-client.pem: LS0tLS1CRUdJTiUyMENFUlRJRklDQVRFLS0tLS0lMEFNSUlEOERDQ0F0aWdBd0lCQWdJVUNpQWVkU3lVa0l6VTlmZ0p6VGFUZU05TW1ITXdEUVlKS29aSWh2Y05BUUVMJTBBQlFBd2NURUxNQWtHQTFVRUJoTUNWVk14RXpBUkJnTlZCQWdUQ2tOaGJHbG1iM0p1YVdFeEZEQVNCZ05WQkFjVCUwQUMxTmhiblJoSUVOc1lYSmhNUlF3RWdZRFZRUUtFd3RSZFdGdWRHbHNJRWx1WXpFTU1Bb0dBMVVFQ3hNRFVVTkQlMEFNUk13RVFZRFZRUURFd3ByZFdKbGJHVjBJRU5CTUI0WERURTRNVEF6TURFd05ESXdNRm9YRFRJek1UQXlPVEV3JTBBTkRJd01Gb3djakVMTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnVENrTmhiR2xtYjNKdWFXRXhGREFTQmdOViUwQUJBY1RDMU5oYm5SaElFTnNZWEpoTVJRd0VnWURWUVFLRXd0UmRXRnVkR2xzSUVsdVl6RU1NQW9HQTFVRUN4TUQlMEFVVU5ETVJRd0VnWURWUVFERXd0cmRXSmxMV05zYVdWdWREQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQJTBBQURDQ0FRb0NnZ0VCQU1Qcnl4QjhpQjFvUytRd3IzTGRSWmlIUXRERElUOHZ3bitVNFAyRmU1VlN5TkxGYkFnMyUwQUVESW4raWF0Mno2dXFNUGd6SzdGb0RjOXhpRTJycVNOZlBlck9ZbGNTamtuNWV4TEdLdVR6WDVwVUJPbGlEaHAlMEFxUzV6U0F0MVp3U204dENUOEdXNDNJWmZQRTVHWTkzdlV4NmxCbUdnVUlrQ1g2b1pXdzFlbmRoS1hpUitWaGc0JTBBZFhBczFHd0MraXFlMldqTWpOVHcxK0I1bGZRbFY2UHJGT092eG12alFFM3Fvc1FHSGxWTS9PblB3MW5Hc2ZodiUwQXFxcVFwVW1IdG5pQzRvdVlxZjIydFdrR0lOdjF4bkVwV21KMm1IZE1XNG5OZVZEWllPZ3p4UU8xMzlvV0E0clAlMEFwZ1FJbDRvQlN2cG5kUnBsbGVubzliaGpYZFlUWlpJd0tnRUNBd0VBQWFOL01IMHdEZ1lEVlIwUEFRSC9CQVFEJTBBQWdXZ01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQSUwQU1CMEdBMVVkRGdRV0JCUVFuVmZIWEdtZy9JRm01RWJDeWs5SVhHU29RREFmQmdOVkhTTUVHREFXZ0JSeVB0WXQlMEExU3YyNFBObno1STdtSHg0MTNOVWp6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFHTENJWXI2U1Q0d3Uzd2k2JTBBKzBTdzAxeVRpaFYrN1JMdHNTS3RpWStidGtpYzJUMk92dzlBQy81aDd6aHpTeGhUampQZituUzNoTEJCK0FGcSUwQTdBenJZaVlQRW1zblJjYVRLTk9uMkF4Y1VuM3ZmSTJjcnU0UEsxNTl3VlR3NTBmR1N4VnpscmNYNlFwdXM5RjQlMEFvTlA3dnExSWYveWhRM01PMnZLejIzMGEzNXd0YkJ0NW5adlRoS3BicG42a3lHOWtsM2ZveHBETFpod0ZuTkc4JTBBZzArRzd0VEJZYmR3N2NWSFc2Tmg0RXF4T1ZGSmJBWjh3ZUsvZ0N6T09maUhLYnpxdlU1VDc1eHBWdTVYOGIrcCUwQUNOeWJIU3c0S1pEaDNHanRyNlo1OUhaSUpGZ0x3WTBaK1FYaEtzdmlySkVsTUlqVW5kUnNoYlpsZnlPRktCTmElMEFnZXlRSWclM0QlM0QlMEEtLS0tLUVORCUyMENFUlRJRklDQVRFLS0tLS0=
  kube-client-key.pem: LS0tLS1CRUdJTiUyMFJTQSUyMFBSSVZBVEUlMjBLRVktLS0tLSUwQU1JSUVvd0lCQUFLQ0FRRUF3K3ZMRUh5SUhXaEw1REN2Y3QxRm1JZEMwTU1oUHkvQ2Y1VGcvWVY3bFZMSTBzVnMlMEFDRGNRTWlmNkpxM2JQcTZvdytETXJzV2dOejNHSVRhdXBJMTg5NnM1aVZ4S09TZmw3RXNZcTVQTmZtbFFFNldJJTBBT0dtcExuTklDM1ZuQktieTBKUHdaYmpjaGw4OFRrWmozZTlUSHFVR1lhQlFpUUpmcWhsYkRWNmQyRXBlSkg1VyUwQUdEaDFjQ3pVYkFMNktwN1phTXlNMVBEWDRIbVY5Q1ZYbytzVTQ2L0dhK05BVGVxaXhBWWVWVXo4NmMvRFdjYXglMEErRytxcXBDbFNZZTJlSUxpaTVpcC9iYTFhUVlnMi9YR2NTbGFZbmFZZDB4YmljMTVVTmxnNkRQRkE3WGYyaFlEJTBBaXMrbUJBaVhpZ0ZLK21kMUdtV1Y2ZWoxdUdOZDFoTmxrakFxQVFJREFRQUJBb0lCQUVXejJlYmZwejF2SWJEcCUwQWNVSVlYdTVKRVFoY283TnJObk5WY0VaQit4bkEvaG1laXpUUkFqNFY0dlZuM1J5TDN4YnhIMkQraG1XZzRLQm8lMEFaL0c3Tkw2WWVEdmFUYjNQNkFrTkhwWE1XOHVoaEErNVVLRmhWZ05rbURrYlo2OU1CZzhXMHV3ZHZMZEJvcDdtJTBBaEJrdFVCRVMvUlkyaHZCM203bFVsQVJKcVRhTmZ3UkROVWQ2VVpUTWl2YnBmMjRseERZaVJSYS9DRTlZWDI2QSUwQWFqRGNRR3BGU1FiWTNzUHRkV0tSWkJvWmFEUjVQekM4MGVRU3hZdmpwQ3VJdU1rRWw5ODRuWEE3M0cyVEtxQ2UlMEFOckFtMDNhNUxva2hSYVVhbXR4OCtWMk16VisvcDB4b2JWcEdWOGtsaTdkMTZaSHNsWStPS3dKSERaTlJaVWR0JTBBdXBlYitWRUNnWUVBMFpUQjhSS3Z2Zjd3S1labzYzQ0VVQmNKNGJiSFA5cmgrVkRhSTZGMDd6dTh3azZacXo2TyUwQW5KVWcxR3FkcUdudm03OXZWWWhZQWtxRHJ0YUNGcXhYcjhLTjZja2d6U2xUWFJvRnRxc0EzM1RJMnU4Vloya3klMEF4RTZrR1ZkVjdiZjNvdUVtTTFzTkYxVWwrYkRRZmJWYnlrQy9keHFzdTNyeWRDUS9aTU9jcW5jQ2dZRUE3MUNEJTBBVStocnJNZWxHNlFvaS94b1B2ZDdJazBRNE0vMTM4SG9FbVhvNUVjaWRLRzViTEMyaG9Nay9DU1l1eEoxaGxBZSUwQWdId3BwWDNGTXhEUGpxWjR2NWJ0QXNhN1JrTWczYUM1NnYwS0Y4bW9sbzBYZWtXVXNNMXJpdEl4ZVN3K0RRNk0lMEFMK1ljdmpWWk93Vm1CUUQrRHZCRkU1citaR0FsMlpGTHFJOXY5VWNDZ1lFQXdqelBQaUVtZGIxSVVnUDdTM0Y5JTBBZjBqSzVNRmtpdDdPbmlWNzlwZlY2ejcvSTBwN2kwVXdJUmpwVTFUNGh6U2ZXRWFrNWEyMmUzRVorRGxnV2FraSUwQW40ZDl4UldkNitjSUZ2cGVIenovVXhwR2FQbzZhUndMYS9yQ2hhWDJ3cG5FemRWRGRVZEdxOEJEc05WWmRaaFclMEEyTzBIUmxpWGpDNVhkS0ovaW1EczJ1TUNnWUJ4SkJkeXJBZDhBRWRHOGkxWlFWUG5zUWsrQmtGY2gvVXVmSFpEJTBBZkhyR3NmclFPVVY0NVhMbDFVcS9DbTVLdzBkYzRMUUsrcWlWM1FoR1JFUmNwTWVoakxFeEJ0T3pQRGxsam45WCUwQVlacEw5TU1IcWx6WEtkNUtXRlBucGNoT0NXU3N0NXYvYVVOZGljdE41QmQvZGlDbTMyRkpDNVlKem9zV2VXTFQlMEFwanpBTVFLQmdGRzB0THpyd3JyZXZhWFgvbnBuNTN1S0dGUGYvTHEvT05icUF4VUFNQlE2T241NnU2WFpkYUdTJTBBVzRzL2lISjAyMXRKUlpZek1pR1JPVWw0WEZqMW5PNURXTG9GRjRZWWw2YW5tOExkZC9vNlRmRjFEc0luMm5MaSUwQWVCL0IwUDQ2Ukp5NVF5YjJLejJpWk80blZ0TUFGSThJTjl0cy9UZXFoaE14bUVDeXRaTU4lMEEtLS0tLUVORCUyMFJTQSUyMFBSSVZBVEUlMjBLRVktLS0tLQ==
kind: Secret
metadata:
  name: kubelet-secret
  namespace: kube-system
type: Opaque


